modLoader="javafml"
loaderVersion="[${loader_version},)"
issueTrackerURL="https://github.com/pupnewfster/ProjectExtended/issues"

[[mods]]
    modId="projectextended"
    version="${version}"
    displayName="ProjectExtended"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/projectextended"
    authors="pupnewfster"
    credits="xnuL for creating the textures"
    description='''ProjectExtended is a mod that adds features to ProjectE that EE2 would probably have had it been made in modern times.'''

[[dependencies.projectextended]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    side="BOTH"
[[dependencies.projectextended]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    side="BOTH"
[[dependencies.projectextended]]
    modId="projecte"
    mandatory=true
    versionRange="[${projecte_version},)"
    side="BOTH"